[package]
name = "hachi"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
tetris = { git = "https://github.com/nightcrab/sunbeam" }
bot = { git = "https://github.com/nightcrab/sunbeam" }
features = { path = "../features" }
minilp = "0.2.2"
rand = { version = "0.8", features = ["small_rng"] }
rand_distr = "0.4"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "nash_NxN"
harness = false

[env]
BINDGEN_EXTRA_CLANG_ARGS = "-std=c++17"